### ISSUE TITLE
[derive] `derive Inductive ...` restricts the grammar

### ISSUE THREAD

**Issue by Columbus240** [LPCIC/coq-elpi#267]
The second phrase results in a syntax error. It shouldn’t.
```coq
Inductive unit := tt.
derive
Inductive unit' := ttt.
```

For reference, the following works: `derive Inductive unit' := | ttt.` with and without the `derive`.

**Comment by gares** [comment]
This bug is already fixed in the coq-master branch: when Coq 8.14 will be out (a matter of weeks) I will release a version of Coq-Elpi based on that branch. Before 8.14 the grammar entry to parse inductive types was not exported by Coq, so I had to "approximate" it in Coq-Elpi.

I'll close this bug once the release is done. Thanks for reporting.

**Comment by Columbus240** [comment]
You're welcome. I didn't figure out how to `opam pin` coq to the dev-branch.  So I used v8.13.2 for now, but with the master branch of coq-elpi.
Aside: I found a [note on Zulip](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Installing.20development.20Coq.20with.20OPAM/near/229324856) on how to `opam pin` coq.

**Comment by gares** [comment]
I think using stable Coq is a sound choice. I was just attaching some context to the bug.

**Comment by gares** [comment]
This is fixed, we now use the same grammar entry Coq uses
