### ISSUE TITLE
[derive] Doesn't automatically add some `param1`

### ISSUE THREAD

**Issue by Columbus240** [LPCIC/coq-elpi#268]
I think this is a design decision, which may be handled either way.
Current behaviour:
```coq
Inductive unit := tt.
Elpi derive unit.
Definition foo := unit.eq.
Fail Elpi derive.param1 foo. (* because [unit.eq] doesn’t have [param1] *)
Elpi derive.param1 unit.eq.
Elpi derive.param1 foo.
```

It would facilitate usage if the `derive.param1 unit.eq` was done automatically during `derive unit` or during `derive.param1 foo`. You might chose to leave it as is, because it might clutter the namespace/searchspace/database, slowing down later commands etc.

A more complicated example of `foo` can be seen in #266.

You could solve this using a "backtracking-derive", which would try to automatically derive the missing dependencies. This behaviour could be triggered by using a differently named command, a wrapper, an optional argument or an attribute.

**Comment by gares** [comment]
I prefer to build it upfront. It's very easy to add

https://github.com/LPCIC/coq-elpi/blob/79a1c189a0f3aaeec4d2269e2d05ab15095fb07b/apps/derive/elpi/derive.elpi#L59-L77

but we need:
- a name for it, so that one can enable/disable it via `#[only]` for example
- a name for the generated constant, I don't think `t.is_eq` is a good one, so we need to find something more informative.

**Comment by gares** [comment]
I mean, it's enough to add one line like
```
derive "XXX"         (derive.param1.main (const YYY)            {calc (Prefix ^ "ZZZ")}), 
```
after line 68. YYY (the constant for eq, is an internal detail up to me), but XXX and ZZZ are something the user will see, so I need decent names.

**Comment by Columbus240** [comment]
This table looks surprisingly simple. How about `t.eq_param1`?

**Comment by gares** [comment]
ok, let be it.
