### ISSUE TITLE
`coq.TC.get-inst-prio` reports wrong priority

### ISSUE THREAD

**Issue by Janno** [LPCIC/coq-elpi#716]
```coq
Require Import elpi.elpi.

Class Test : Prop := {}.

Instance instance_c : Test := Build_Test.
Instance instance_g : Test | 4 := Build_Test.

Definition hint_c : Test := Build_Test.
Definition hint_g : Test := Build_Test.

Hint Resolve hint_c : typeclass_instances.
Hint Resolve hint_g | 5 : typeclass_instances.

Elpi Command test.
Elpi Accumulate lp:{{
  pred show i:gref.
  show Class :- std.forall {coq.TC.db-for Class} (show.inst Class).
  pred show.inst i:gref, i:tc-instance.
  show.inst Class (tc-instance Instance P1) :-
    coq.TC.get-inst-prio Class Instance P2,
    coq.say Instance "," P1 "," P2.
}}.
Elpi Query lp:{{ show {{:gref Test}} }}.
(*
Output:
<<
const «hint_c» , tc-priority-computed 0 , tc-priority-computed 0
const «instance_c» , tc-priority-computed 0 , tc-priority-computed 0
const «instance_g» , tc-priority-given 4 , tc-priority-given 4
const «hint_g» , tc-priority-computed 0 , tc-priority-computed 0
>>

BUG: <<hint_g>> should have <<tc-priority-given 5>>.
```

Found by @swasey

**Comment by gares** [comment]
CC @FissoreD

**Comment by gares** [comment]
I guess internally the two priorities are not stored in the same place. Is this expected @mattam82 ?

**Comment by FissoreD** [comment]
Mh, I think I've found where to get the prio.

If I understand correctly, when we declare an Instance with a user-defined prio $P$, $P$ is put in the hint_priority field of the instance.

https://github.com/coq/coq/blob/303a7c24ddd383d894b90b98178e2e8ee89f675a/pretyping/typeclasses.ml#L23C1-L26C1

If the prio is not set, then the same field is set to None, and it is in that situation that we try to figure out the approximated priority of the instance by counting the number of its hypothesis.

https://github.com/LPCIC/coq-elpi/blob/11a121e2e20013d01e0c70ce2d3b737415c0c624/src/coq_elpi_builtins.ml#L445-L464

Apparently the instruction:
`Hint Resolve hint_g | 5 : typeclass_instances.`
adds the instance but put None into the field hint_priority.

I've dug a bit into the coq code and found that there is a map: `Hints.searchtable_map` which contains per each database (ours is typeclass_instances) a list of gref with their priority. In that map `hint_g` has actually priority 5.

I will try to provide a patch to the problem soon

**Comment by FissoreD** [comment]
Hello @swasey and @Janno,

In [this](https://github.com/LPCIC/coq-elpi/pull/717) PR I propose a solution where the priority of rules added via Hint Resolve are correctly retrieved by the coq-elpi.

It seems, that it is not possible to know if the priority is "tc-priority-given" or "tc-priority-computed" for definitions added via Hint Resolve.

That's why I've changed the signature of get_inst_prio into `pred coq.TC.get-inst-prio i:gref, i:gref, o:int.` where the int is the prio of the instance. 

With this change I also remove the type `tc-priority`.

In your implementation, do you need to know if the priority is given by the user or computed?

If you need it, I could manage to reuse the old algorithm to get this piece of information (note that, for hints, I will return in all cases tc-priority-computed)
